version: '2'
services:
    php:
        container_name: laravel_realtime_php
        build: .docker/php
        volumes:
            - .:/home/wwwroot/test
        links:
            - test_redis
            - node

    node:
        container_name: laravel_realtime_node
        build: .docker/node
        ports:
            - 6001:6001
        links:
            - test_redis

    db:
        image: mysql:8.0
        command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
        container_name: laravel_realtime_mysql
        restart: always
        ports:
            - '6603:3306'
        environment:
            MYSQL_ROOT_PASSWORD: helloworld

    app:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: always
        ports:
            - '8080:80'
        environment:
            PMA_HOST: db
#    mongo:
#        image: mongo
#        container_name: laravel_realtime_mongo
#        restart: always
#        environment:
#            MONGO_INITDB_ROOT_USERNAME: root
#            MONGO_INITDB_ROOT_PASSWORD: example
#            MONGO_INITDB_DATABASE: test
#        volumes:
#            - .docker/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

    apache:
        container_name: laravel_realtime_apache
        build: .docker/apache
        ports:
            - "8000:80"
        volumes:
            - .:/home/wwwroot/test
        depends_on:
            - php

#    mongo-express:
#        image: mongo-express
#        container_name: laravel_realtime_mongo_express
#        restart: always
#        ports:
#            - 8081:8081
#        environment:
#            ME_CONFIG_MONGODB_ADMINUSERNAME: root
#            ME_CONFIG_MONGODB_ADMINPASSWORD: example

    test_redis:
        container_name: laravel_realtime_redis
        image: 'bitnami/redis:latest'
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
        ports:
            - "6379:6379"
